# Generated by Django 3.0.5 on 2020-04-13 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('url_short', models.CharField(max_length=50, unique=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('creator_ip', models.CharField(max_length=15)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='shorturl.Protocol')),
            ],
        ),
    ]
