# Generated by Django 3.0.5 on 2020-04-09 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='download',
            old_name='content_id',
            new_name='object_id',
        ),
        migrations.RenameField(
            model_name='hint',
            old_name='content_id',
            new_name='object_id',
        ),
    ]
