# Generated by Django 3.0.5 on 2020-04-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('time_delete', models.DateTimeField()),
                ('password_for_read', models.CharField(blank=True, max_length=40, null=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('creator_ip', models.CharField(max_length=15)),
                ('url', models.CharField(max_length=32)),
            ],
        ),
    ]
