# Generated by Django 3.0.5 on 2020-04-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesharing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='unique_hash_for_url',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='uploads/filesharing/%Y/%m/%d/'),
        ),
    ]
